name: Auto Deploy hugo
on:
  push:
    branches:
      - master # 更新触发的分支
jobs:
  build-deploy:
    #  runs-on: ubuntu-latest
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
           submodules: recursive # Fetch Hugo themes (true OR recursive)
           fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          #  hugo-version: "latest" # 可以修改为你使用的 Hugo 版本
          hugo-version: "0.113.0"
          extended: true # 设置是否需要 extended 版本

      - name: Cache resources # 缓存 resource 文件加快生成速度
        uses: actions/cache@v2
        with:
         path: resources
         # 检查照片文件变化
         key: ${{ runner.os }}-hugocache-${{ hashFiles('content/**/*') }}
         restore-keys: ${{ runner.os }}-hugocache-

      - name: Build Hugo static files # 部署静态资源
        run: hugo --gc --minify

      - name: Deploy to Github Pages  # 部署到Github Pages页面
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }} # 两个仓库请使用 deploy_key
          external_repository: woniu336/woniu336.github.io  # 如果在同一个仓库请注释
          publish_dir: ./public # hugo 生成到 public 作为跟目录
          publish_branch: main # Github Pages 所在分支
          commit_message: ${{ github.event.head_commit.message }}
